Customize downsample, depth of coverage, and genome size per sample
bioforensics/yeat pull request #77
Opened 2024-04-15 17:23 UTC by danejo3

2024-04-17 15:22 UTC, danejo3 reviewed
This MR is ready for review! @standage A lot of file changes; however, most changes are adding `downsample`, `genome_size`, and `coverage_depth` to the json data. After this merge, we'll cut a new release for YEAT!

2024-04-17 15:22 UTC, danejo3 commented on yeat/tests/test_config.py
> -def test_invalid_assembly_algorithm():
Moved tests to different modules: `test_sample.py` and `test_assembly.py` for organization. Keeping `test_config.py` to contain tests testing for the `AssemblyConfig` class object.

2024-04-18 19:52 UTC, standage requested changes
Looks good! As you said, there were lots of little updates to account for the new config structure, but the primary code changes were clear and straightforward to follow.

There's one function that I don't think fared very well in this update: see below.

2024-04-18 19:52 UTC, standage commented on yeat/workflow/__init__.py
> +            sample[key] = value if key in DOWNSAMPLE_KEYS else get_resolved_paths(value)
This code was updated, but it still needs some work. Changing `readtype, reads` to `key, value` reflects the wider scope of the function, but it also makes the code harder to understand. Also, the name of the function suggests that it's working only with paths, but that's no longer true.

2024-04-19 14:47 UTC, danejo3 commented on yeat/workflow/__init__.py
> +
Thoughts on the newly refactored function? @standage Other than that, this is PR is ready!

2024-04-19 18:55 UTC, standage approved these changes

2024-04-19 18:55 UTC, merged